### ISSUE TITLE
select only one file when EXTRA_ALLOW_MULTIPLE == true

### ISSUE THREAD

**Issue by dontspeak** [spacecowboy/NoNonsense-FilePicker#105]
Hello, I get the following behavior and I do not know whether this is intended or not:

1) Open FilePicker with
```
FilePickerActivity.EXTRA_ALLOW_MULTIPLE, true);
FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);
FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
```

2) Select **one** file, click _ok_
-->returning to start path, nothing else happens

3) Click _ok_ again
--> Getting message _Please select something first_

4) Selecting another file, click _ok_
--> Returning in `onActivityResult `with both files in `ClipData`

So for me it is not possible to on the one hand start the picker with **multiselect** and on the other hand **just choose one file** finally.

From my point of view there are thousand possible usecases that the application developer wants the user to **_potentially_** select multiple files, but maybe also only one.

Does the described behavior is "works as designed"?

Thank you very much in advance.

**Comment by dontspeak** [comment]
I'm sorry to bother you, the problems was: By error, my filepicker was started **TWICE** immediatly successively. So the first return to the start path was just the display of the secondly started Filepicker... 

Nevertheless interessting that `onActivityResult `was only called once with both files in ClipData.

**Comment by spacecowboy** [comment]
Great that you found the problem.

Interesting indeed that Android would bunch those two results together like that.
