### ISSUE TITLE
Is it possible to enable thumbnails for .MODE_FILE ?

### ISSUE THREAD

**Issue by yigitserin** [spacecowboy/NoNonsense-FilePicker#109]
Hey there,

I want to be able to pick both files and multimedia. But I also would like to see a preview of the images I pick. Is there any way to enable thumbnails for this case?

Thanks.

**Comment by spacecowboy** [comment]
Just do what the sample app shows you: https://github.com/spacecowboy/NoNonsense-FilePicker/tree/master/sample/src/main/java/com/nononsenseapps/filepicker/sample/multimedia

If you have any specific questions, or run into any issues, don't hesitate to ask.
