### ISSUE TITLE
Does this support requesting permissions at runtime which is required from API 23

### ISSUE THREAD

**Issue by kal27** [spacecowboy/NoNonsense-FilePicker#111]
Hey does this file picker support the requesting permissions to write in external storage at runtime which is necessary from API 23 onwards?
Google forces the developers to ask for permissions at runtime(rather than at app install) starting with androind marshmellow

Thanks

**Comment by spacecowboy** [comment]
Yes, from version 2.3.0 and up:
https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/v2.3.0
