### ISSUE TITLE
 Modify the bottom button to display the text

### ISSUE THREAD

**Issue by IT-crackpot** [spacecowboy/NoNonsense-FilePicker#124]
Thanks
      
How do I change the text at the bottom

**Comment by spacecowboy** [comment]
@IT-crackpot what button?

**Comment by IT-crackpot** [comment]
OK and cancel. I want change the text

**Comment by spacecowboy** [comment]
As with any android stuff, look in the relevant layout files.

The buttons are defined here:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/res/layout/nnf_fragment_filepicker.xml#L65

Here's some stuff you might wanna read: https://developer.android.com/guide/topics/ui/declaring-layout.html

**Comment by IT-crackpot** [comment]
Thanks
