### ISSUE TITLE
Unable to filter files to show only pdf, images and videos

### ISSUE THREAD

**Issue by fast1234** [spacecowboy/NoNonsense-FilePicker#125]
I am using intent filter to show files which are PDF, images or videos which showing files. But when I use following code it is showing images and videos only no pdf is shown. Is there any way to tweak the code
 ```
 String[] ACCEPT_MIME_TYPES = {
                          "image/*",
                        "application/pdf",
                        "video/*"
                };
                i.putExtra(Intent.EXTRA_MIME_TYPES, ACCEPT_MIME_TYPES);
```

Please provide some way to do this. i here is the intent.

**Comment by spacecowboy** [comment]
See
http://spacecowboy.github.io/NoNonsense-FilePicker/example/filter_file_extension/

Den 4 jan. 2017 08:18 skrev "yash kumar jain" <notifications@github.com>:

**Comment by fast1234** [comment]
Thanks for the reply. Will it be possible to show Directory only if pdf, txt, image file is present in that folder. I mean by default it is showing system Directories  as well. I need to show only those directories  which have at least one of the required files like pdf,txt, image.

**Comment by spacecowboy** [comment]
@fast1234 The library is intended to be a base for your own implementation, so go ahead and implement that if you want it.

**Comment by fast1234** [comment]
ok thanks for the help. :+1:
