### ISSUE TITLE
'Select file' is shown instead of 'Select folder'

### ISSUE THREAD

**Issue by sevar83** [spacecowboy/NoNonsense-FilePicker#14]
Happens with

intent.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_DIR);

**Comment by spacecowboy** [comment]
And you are using version 1.2 ?

**Comment by sevar83** [comment]
No, still 1.1.3. Will try 1.2 in a minute.

**Comment by sevar83** [comment]
Could you publish it on jcenter, please?

**Comment by spacecowboy** [comment]
No problems for me, but I'll have to read up on how.

**Comment by sevar83** [comment]
This might be of help to you:
https://github.com/novoda/bintray-release/blob/master/README.md

**Comment by spacecowboy** [comment]
Thanks, that actually helped a lot. v2 should be up on jcenter fairly soon. I've uploaded to bintray and requested it to be included on jcenter.

**Comment by spacecowboy** [comment]
It was apparently already up on JCenter, but I now have direct publishing control. Will use this going forward because Sonatype makes me want to punch someone.

**Comment by spacecowboy** [comment]
I am not able to replicate the issue btw. It works fine in my notepad app (1.2.0 that is)

https://github.com/spacecowboy/NotePad/blob/0ff742180879feacdbdf376bd0f735a001baee7a/app/src/main/java/com/nononsenseapps/notepad/prefs/SyncPrefs.java#L192

The file-mode is the default mode however, so I suspect that the mode somehow is not being sent to the activity. Double check that you are not creating a second intent, or somehow overwriting the extra value with something else.

**Comment by sevar83** [comment]
I've seen you removed the "Select file" and "Select folder" strings in a recent commit. So, without them it's fine. You should close the issue.
But there's another problem - it cannot survive rotation.

**Comment by spacecowboy** [comment]
Ah, maybe just the labels were wrong then?

I've opened a new issue for that, which is definitely present.. #15

**Comment by spacecowboy** [comment]
And fixed in 2.0.4
