### ISSUE TITLE
Clarification regarding the path returned in the Uri

### ISSUE THREAD

**Issue by AdityaAnand1** [spacecowboy/NoNonsense-FilePicker#140]
When picking a directory in older versions of the library, I used to get (for example):

    /storage/emulated/0/DCIM

Now I get:

    /root/storage/emulated/0/DCIM

When I try to check for the existence of `new File("/root/storage/emulated/0/DCIM").isDirectory()`, it returns that the file does not exist. But `new File("/storage/emulated/0/DCIM").isDirectory()` works just fine.

So, as a workaround I just snip out "/root" from the returned path and then I can use it as before. I'm wondering why was this change made and whether I'm handling it correctly. That is, is there any other way to get a File reference from the "/root" path?

**Comment by spacecowboy** [comment]
This sounds like a bug or possibly a misconfiguration. Could add some more details?

If you look at the sample app, you'll notice that it does not have a `/root` prefix in the result so I'm confused why you do.

**Comment by VSG24** [comment]
I'm having this problem as well. File paths returned by this library all have a `root` prefix.

**Comment by spacecowboy** [comment]
@AdityaAnand1 please follow @VSG24 's advice and use the provided utility method. Does that fix your issue?

**Comment by AdityaAnand1** [comment]
I'm already using this though:

     List<Uri> files = Utils.getSelectedFilesFromResult(data);

What's weird is that even in a completely new project I'm seeing the same thing (in different emulators and physical devices) and that is after exactly following the instructions in the Readme. I'm going to try and dig up some more info.

**Comment by spacecowboy** [comment]
Yes but you must also use

Utils.getFileForUri(uri).toString()

With the URI you get from Utils.getSelectedFilesFromResult

It's simply how the fileprovider works.

As can be seen in the Java docs:

    /**
     * Convert a uri generated by a fileprovider, like
content://AUTHORITY/ROOT/actual/path
     * to a file pointing to file:///actual/path
     *
     * Note that it only works for paths generated with `ROOT` as the path
element. This is done if
     * nnf_provider_paths.xml is used to define the file provider in the
manifest.
     *
     * @param uri generated from a file provider
     * @return Corresponding {@link File} object
     */

I did not update the README enough after this change it seems. Will make
sure to do that.

Den 21 apr. 2017 04:20 skrev "Aditya Anand" <notifications@github.com>:

**Comment by spacecowboy** [comment]
Have now updated the README: https://github.com/spacecowboy/NoNonsense-FilePicker/commit/c8c4084b80d3d073cfe9e9512ae6f9b57f4ce194

hopefully this avoid future confusion

**Comment by AdityaAnand1** [comment]
Yup, that did it :)
