### ISSUE TITLE
Can't get selected filepath after updating Nativescript to 3.x

### ISSUE THREAD

**Issue by kumaran-dena** [spacecowboy/NoNonsense-FilePicker#145]
I have used nativescript-file-picker plugin to provide file attachment option.

Its working fine when my development environment is like followed.
nativescript │ 3.0.3
tns-core-modules │ 2.5.2
tns-android │ 2.5.0
After updated Nativescript to 3.x, like followed.
nativescript │ 3.0.3
tns-core-modules │ 3.1.1
tns-android │ 3.1.1

This time Can’t able to get selected file path. But before updation i can able to get.

After i have tried with followed links.
https://github.com/NativeScript/NativeScript/issues/4032
https://github.com/NativeScript/NativeScript/wiki/Migrating-Plugins-to-NativeScript-3.0
But i still facing same problem.

Thank you…

**Comment by spacecowboy** [comment]
what the heck is NativeScript? And how is it related to this project?

**Comment by spacecowboy** [comment]
@kumaran-dena you have reported an issue on the wrong project. I have no idea what nativescript is but I can tell you that this page: https://www.npmjs.com/package/nativescript-file-picker
is using a README file from this project for some unknown reason.

This project has nothing to do with anything javascript.
