### ISSUE TITLE
apply plugin: 'bintray-release'

### ISSUE THREAD

**Issue by anonym24** [spacecowboy/NoNonsense-FilePicker#146]
I want to add your library locally (copy library from github to my project)

but what is `apply plugin: 'bintray-release'`?

_Error:(9, 0) Plugin with id 'bintray-release' not found._

**Comment by spacecowboy** [comment]
it's for publishing the library to bintray, which is where it is downloaded from when you add a dependency to it in your gradle file.

The bintray-release plugin is downloaded via this buildscript-dependency:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/build.gradle#L15
