### ISSUE TITLE
Can I make it say something other than "Ok" and "Cancel"?

### ISSUE THREAD

**Issue by AdityaAnand1** [spacecowboy/NoNonsense-FilePicker#156]
In some situations, "Add" or "Insert" or "Back" or something else may be more appropriate. I didn't spot any examples that do this in the wiki. Is this currently supported? 

Plus, we can use this behavior for internationalization.

**Comment by spacecowboy** [comment]
A good spot! Currently they can't be overridden without supplying entirely different layout files (a lot of copy paste for just changing a string).

I've added the ability to define them in your local app in https://github.com/spacecowboy/NoNonsense-FilePicker/pull/157 just like the other strings. The default remains the same android specific ok/cancel strings which are translated to all system languages.
