### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by jangrewe** [spacecowboy/NoNonsense-FilePicker#159]
Hi, i'm seeing a couple of crash reports in Crashlytics that seem to be caused by your library:
```
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {org.faked.isms2droid/com.nononsenseapps.filepicker.FilePickerActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```
```
Caused by java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState
android.support.v4.app.FragmentManagerImpl.checkStateLoss (SourceFile:2044)
android.support.v4.app.FragmentManagerImpl.enqueueAction (SourceFile:2067)
android.support.v4.app.BackStackRecord.commitInternal (SourceFile:680)
android.support.v4.app.BackStackRecord.commit (SourceFile:634)
com.nononsenseapps.filepicker.AbstractFilePickerActivity.onResume (SourceFile:108)
android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1267)
android.app.Activity.performResume (Activity.java:6237)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:3453)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3499)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1576)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:194)
android.app.ActivityThread.main (ActivityThread.java:5931)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:987)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:782)
```

According to this post: https://stackoverflow.com/a/10261449/5218832 it is a known bug (https://issuetracker.google.com/issues/36932872) and can be fixed by not calling `super.onSaveInstanceState(b);` (or using the workaround describe there, if you need to save the state).

This would be in this file:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/72333f802c0b398fc53cfd1cd3c20701819aa0df/library/src/main/java/com/nononsenseapps/filepicker/AbstractFilePickerActivity.java#L119

Not sure if this also applies to the Fragment, as i'm not using it... but just in case:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/d107ecc81c5e7444aeb471aa2ed8af0d58f42c7f/library/src/main/java/com/nononsenseapps/filepicker/AbstractFilePickerFragment.java#L500

**Comment by spacecowboy** [comment]
Thanks for the report. Would you consider making a PR for it?

**Comment by jangrewe** [comment]
Done! #160
