### ISSUE TITLE
FilePicker show() Promise is not resolving. Promise's "then" response is not firing

### ISSUE THREAD

**Issue by johnRosalin** [spacecowboy/NoNonsense-FilePicker#166]
I was able to get the directory list modal to display the files, I can check/uncheck the files. but when tapping the "ok" after selecting the items, the FilePicker does not seem to resolve the "show()" promise.

I have already followed the instructions stated on the plugin's README.md
I am using _nativescript 4.2.0_ with _nativescript-angular ~6.1.0_ and _nativescript-file-picker 0.0.2_

here is a code snippet of how I implemented the FilePicker class on my application
```
// browse.component.ts
import { FilePicker } from "nativescript-file-picker";

@Component({
    selector: "Browse",
    moduleId: module.id,
    templateUrl: "./browse.component.html"
})
export class BrowseComponent {
    private fileContent: any;
    selectFilePicker() {
            (new FilePicker()).show()
                .then(filePicked => {
                    // not firing
                    console.log("file Picked: ", filePicked);
                    this.fileContent = filePicked;
                }).catch(err => {
                    console.error("file Picker show err: ", err);
                });
    }
}
```

```
<!-- browse.component.html -->
<ActionBar class="action-bar">
    <Label class="action-bar-title" text="Browse"></Label>
</ActionBar>

<ScrollView>
    <GridLayout rows="auto auto" columns="">
        <Button text="Get Files" (tap)="requestPermissions()"></Button>
        <Label row="1" text="{{fileContent | json}}" textWrap="true"></Label>
    </GridLayout>
</ScrollView>
```

Is there something missing on my implementation or is this because of version incompatability?

**Comment by spacecowboy** [comment]
What's nativescript-file-picker?

If your app is not in Java or Kotlin, then it's unsupported I'm afraid.

**Comment by spacecowboy** [comment]
@johnRosalin I think you're looking for https://github.com/kazemihabib/nativescript-FilePicker

**Comment by johnRosalin** [comment]
Oh I'm sorry about this.
