### ISSUE TITLE
Conflict with ic_launcher.png and no new version on maven repo

### ISSUE THREAD

**Issue by NitroG42** [spacecowboy/NoNonsense-FilePicker#17]
Hi, as seen in my PR : https://github.com/spacecowboy/NoNonsense-FilePicker/pull/16
The ic_launcher.png should be removed from the lib.
By the way, the last version of the lib on the maven repo is 2.0.2 (2.0.4 is not found).

**Comment by spacecowboy** [comment]
Thanks for the pull request!

Just add jcenter to your repositories. For some reason, the Maven stuff just stopped working.

**Comment by spacecowboy** [comment]
To clarify, like the readme mentions, add jcenter to your gradle file:

```
repositories {
    jcenter()
}
```

**Comment by NitroG42** [comment]
Well I did that, but same problem. I'll try later !

**Comment by spacecowboy** [comment]
Hmm, at right this moment there is some connectivity issue with jcenter, so you might be experiencing that.. Can't upload the new version at the moment..

**Comment by NitroG42** [comment]
I'm not in a rush don't worry :) I can wait a few days (and I have my local version for now anyway)
