### ISSUE TITLE
Select folder

### ISSUE THREAD

**Issue by davix10** [spacecowboy/NoNonsense-FilePicker#19]
Hi, is it possible to select a default folder when you launch the intent?
Thanks

**Comment by spacecowboy** [comment]
Yes ( I now realize I have forgotten to document this everywhere)

Use "EXTRA_START_PATH" or "KEY_START_PATH" (activity/fragment):

    intent.putStringExtra(AbstractFilePickerActivity.EXTRA_START_PATH, "/path/to/some/dir/")

**Comment by davix10** [comment]
Thanks a lot! Your library is peferct!

**Comment by spacecowboy** [comment]
:+1:
