### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by marcoRS** [spacecowboy/NoNonsense-FilePicker#21]
Hello, when trying to compile your project locally, I receive the following Gradle build error:

A problem occurred evaluating project ':library'.
> Could not find property 'BINTRAY_USER' on com.novoda.gradle.release.PublishExtension_Decorated@103c97ff.

Maybe some defaults should be provided.

**Comment by spacecowboy** [comment]
Thanks for the report. I added some default values which should fix it.
