### ISSUE TITLE
Make filepicker depend only on EXTRA_ALLOW_CREATE_DIR

### ISSUE THREAD

**Issue by davix10** [spacecowboy/NoNonsense-FilePicker#25]
Hi, how can I create a new folder? I tried to enable this feature using this command: 
iii.putExtra (FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, true);
but I can not figure out whether it should be a button that allows the addition.

Thanks in advance.

**Comment by spacecowboy** [comment]
As it currently is, you also need to be in directory selection mode. This
gives you a button in the action bar. But I should make it depend only on
the create switch.

**Comment by davix10** [comment]
Thanks a lot!
it is also possible to block the path without possibility to move to other directories?

**Comment by spacecowboy** [comment]
It is indeed, in that case you need to override `getParent()` and `getRoot()`. Here's a full example:

```java
import com.nononsenseapps.filepicker.FilePickerFragment;

import java.io.File;

public class RootedFilePickerFragment extends FilePickerFragment {

    /**
     * Return the path to the parent directory. Should return the root if
     * from is root.
     *
     * @param from
     */
    @Override
    public File getParent(final File from) {
        if (getFullPath(from).equalsIgnoreCase(getFullPath(getRoot()))) {
            // We are already at the root directory
            return from;
        } else {
            // Go up like normal
            return super.getParent(from);
        }
    }

    /**
     * Get the root path (lowest allowed).
     *
     * @return File rooted at the Downloads directory
     */
    @Override
    public File getRoot() {
        // Stop at equivalent of /storage/emulated/0/Downloads
        return new File(super.getRoot(), "/Downloads");
    }
}
```

**Comment by spacecowboy** [comment]
With the newest version (**2.1**) you only need to override the `getRoot` method. The picker will not go above the root directory now. Note that the default `getRoot` method was actually incorrect before.

```java
import android.os.Environment;

import com.nononsenseapps.filepicker.FilePickerFragment;

import java.io.File;

public class RootedFilePickerFragment extends FilePickerFragment {

    /**
     * Get the root path (lowest allowed).
     *
     * @return File rooted at the Downloads directory
     */
    @Override
    public File getRoot() {
        // Stop at equivalent of /storage/emulated/0/Downloads
        return new File(Environment.getExternalStorageDirectory(), "/Download");
    }
}
```

**Comment by spacecowboy** [comment]
And if you want to block changing directories all-together, override the `isItemVisible`method and do not add directories to the list.
