### ISSUE TITLE
Create directory icon always shows

### ISSUE THREAD

**Issue by hcoosthuizen** [spacecowboy/NoNonsense-FilePicker#27]
I've extended `FilePickerFragment` and `AbstractFilePickerActivity` to make use of the file picker in my app.  I start the activity with the following:

```java
Intent i = new Intent(getActivity(), FileSelectionActivity.class);
i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);
i.putExtra(FilePickerActivity.EXTRA_START_PATH, FileUtils.getDownloadDirectory().getPath());
startActivityForResult(i, SELECT_FILE);
```

And in the activity, I just create the fragment:
```java
public class FileSelectionActivity extends AbstractFilePickerActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Bundle params = getIntent().getExtras();
        String startPath = params.getString(FilePickerActivity.EXTRA_START_PATH, Environment.getExternalStorageDirectory().getPath());
        boolean allowMultiple = params.getBoolean(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
        boolean allowCreateDir = params.getBoolean(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
        int mode = params.getInt(FilePickerActivity.EXTRA_MODE);
        getSupportFragmentManager().beginTransaction().replace(android.R.id.content,
                                                               getFragment(startPath, mode, allowMultiple,
                                                                           allowCreateDir)).commit();
    }

    @Override
    protected AbstractFilePickerFragment getFragment(String startPath, int mode, boolean allowMultiple, boolean allowCreateDir) {
        AbstractFilePickerFragment<File> fragment = new FileSelectionFragment();
        fragment.setArgs(startPath, mode, allowMultiple, allowCreateDir);
        return fragment;
    }
}
```
But the create directory icon is still visible and selectable once the fragment is visible.  Is there something I'm missing?  I stepped through the source and in `onCreateOptionsMenu()` the create directory item does invoke `setVisible(false)`.

**Comment by spacecowboy** [comment]
Problem is that you insert **two** fragments into the layout. You should not override the onCreate method in your activity. The only thing you should implement is the getFragment method.

What happens now is that inside `super.onCreate` a fragment is created and inserted into the layout (like it should). Once finished, your piece of code runs which replaces something else entirely (are you using a custom layout?). One of the fragments will fail to hide its icon.

Removing the onCreate method entirely fixes the issue. Btw, I am assuming that you have some more code in your `FileSelectionActivity`? If it's just this then you can simply use the included `FilePickerActivity` directly.

**Comment by hcoosthuizen** [comment]
Sorry created #28 literally the same time you answered this issue.  I'm using my own fragment in order to filter for a specific extension, so I extended the `AbstractFilePickerActivity` and overrode `onCreate()` reflexively, silly mistake.

Removing it does fix the issue, thanks.

**Comment by spacecowboy** [comment]
No problem! Glad you found some use for the library :)
