### ISSUE TITLE
Layout from start path remains on screen

### ISSUE THREAD

**Issue by hcoosthuizen** [spacecowboy/NoNonsense-FilePicker#28]
With the same use case as in https://github.com/spacecowboy/NoNonsense-FilePicker/issues/27, another issue I have is when I navigate to another directory, whatever the start directory's content was will remain on the screen and draw over/under the new content.

For example, setting the start folder to /sdcard/emulated/0/DCIM:

![device-2015-06-05-155955](https://cloud.githubusercontent.com/assets/12761964/8007443/18d12ecc-0b9c-11e5-90b3-9a1d8dba0e51.png)

Then navigating up (`..`)

![device-2015-06-05-160048](https://cloud.githubusercontent.com/assets/12761964/8007448/23fdc760-0b9c-11e5-91b3-6d7ad431c3dd.png)

**Comment by spacecowboy** [comment]
Problem is the same as in #27, you are creating **two** fragments.
