### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by kuldeepdhaka** [spacecowboy/NoNonsense-FilePicker#29]
it better to licence under "GPLv3 or later" & "LGPLv3 or later".
for future, this will assure that licence can be upgraded for future needs

**Comment by spacecowboy** [comment]
I believe it is licensed under "LGPLv3 or later" already. If you check the copyright headers in the files, you find:

```
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
```

Should I make this clearer somewhere else perhaps?

**Comment by kuldeepdhaka** [comment]
yes, lgplv3 or later. (in code header, my mistake)

in LICENCE "See COPYING.LESSER and COPYING."
1) clearly mention "LGPLv3 or later" in LICENCE
2) consider doing it "GPLv3 or later" too (any special reason not so?).
(for example: (afaik) while mixing "GPLv3 or later" and "LGPLv3 or later", it make it "GPLv3 or later")

**Comment by spacecowboy** [comment]
Does the changes in https://github.com/spacecowboy/NoNonsense-FilePicker/pull/30 do the trick?

**Comment by kuldeepdhaka** [comment]
i do not think it is a better idea to do change to the licence file.
better specify the "or later" in your LICENCE

**Comment by spacecowboy** [comment]
Right. Fixed.
