### ISSUE TITLE
Allow setting of toolbar text colour

### ISSUE THREAD

**Issue by psyren89** [spacecowboy/NoNonsense-FilePicker#31]
Currently, the colour of the path text in `fragment_filepicker.xml` is hardcoded to `@android:color/white` (https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/res/layout/fragment_filepicker.xml#L41).
Would it be possible to allow customisation of this, in addition to the toolbar colour?

**Comment by spacecowboy** [comment]
Absolutely. I'll get on it when I return from vacation!

**Comment by spacecowboy** [comment]
In version 2.2 it is now possible to set a toolbar theme. You can use this to override the text color like so:

```xml
<style name="SampleToolbarTheme" parent="ThemeOverlay.AppCompat.Dark.ActionBar">
        <item name="android:textColorPrimary">@android:color/white</item>
</style>

<style name="SampleThemeLight" parent="NNF_BaseTheme.Light">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>

        <item name="alertDialogTheme">@style/SampleAlertDialogThemeLight</item>

        <!-- Set your custom toolbar theme like so -->
        <item name="nnf_toolbarTheme">@style/SampleToolbarTheme</item>
</style>
```
