### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by prempalsingh** [spacecowboy/NoNonsense-FilePicker#33]
Where can I see the changelog? I am using an earlier version of the library and want to know what all has changed in the latest version.

**Comment by spacecowboy** [comment]
They are listed here:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/release-notes.md

**Comment by prempalsingh** [comment]
Thanks. I think it would be nice to include a link to release notes in the README.

**Comment by spacecowboy** [comment]
Done
