### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by BackPackerDz** [spacecowboy/NoNonsense-FilePicker#34]
Hi with the version 2.2, I got this error 

/home/brio/AndroidstudioProjects/DzBacNext/app/src/main/AndroidManifest.xml
Error:(29, 9) Attribute application@label value=(@string/nnf_app_name) from com.nononsenseapps:filepicker:2.2:29:9
Error:(29, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/nnf_app_name) from com.nononsenseapps:filepicker:2.2:29:9
  	is also present at net.the4thdimension:poly-picker:1.0.11:13:9 value=(@string/app_name)
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:29:5 to override
Information:BUILD FAILED

**Comment by spacecowboy** [comment]
Have a look at 6d6adef, it illustrates how you can solve it by doing what the error message suggests.

I have also changed the code to prevent such conflicts in the future.

**Comment by spacecowboy** [comment]
v2.2.1 an onwards will not generate the same conflict.

**Comment by BackPackerDz** [comment]
Thanks ! :+1:
