### ISSUE TITLE
Can this picker create a directory while in a directory-picker-activity?

### ISSUE THREAD

**Issue by MewX** [spacecowboy/NoNonsense-FilePicker#36]
It's very common to create directory when picking a directory. Is there a way to show "create folder" button?

P.S. The "OK", "Cancel" button will be more artistic if using boardless ripple effects.

**Comment by spacecowboy** [comment]
Yes, indeed it is. Just make sure to enable the EXTRA_ALLOW_CREATE_DIR argument (pass True).

Thanks for the "artistic tip". I might try and improve them.

**Comment by MewX** [comment]
Thanks!
