### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by AviFix** [spacecowboy/NoNonsense-FilePicker#37]
Hi,

Thanks for your work.

I was wondering if it is possible to set a specific file type such as audio?

Thank's a lot

Avi

**Comment by spacecowboy** [comment]
Not built-in but the Wiki has an example where the list is filtered on extensions:
https://github.com/spacecowboy/NoNonsense-FilePicker/wiki/Example:-Filter-on-file-extensions

So if you make a list of audio file extensions:

```java
List<String> places = Arrays.asList("mp3", "wav", "ogg");
```

You could for example do:

```java
return ExtensionsList.contains(getExtension(file).toLowerCase());
```

Instead of the example's
```java
return EXTENSION.equalsIgnoreCase(getExtension(file));
```

**Comment by AviFix** [comment]
Perfect.

Thank's a lot

Avi

**Comment by spacecowboy** [comment]
Np
