### ISSUE TITLE
FilePicker cannot be used with non-touchscreen devices

### ISSUE THREAD

**Issue by RBWare** [spacecowboy/NoNonsense-FilePicker#44]
Trying to use a keyboard, or directional pad to navigate the file picker does not work. Only "Cancel" and "Okay" can be selected.

**Comment by spacecowboy** [comment]
Hmm. Never tested this. Will see what can be done.

**Comment by spacecowboy** [comment]
Have a look at [2.3.1](https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/v2.3.1) and corresponding sample app. My tests on the emulator indicates that it works now.
