### ISSUE TITLE
Displaying image thumbnails in file browser

### ISSUE THREAD

**Issue by LinkedHK** [spacecowboy/NoNonsense-FilePicker#47]
Hi, I just has got project and custom implementation  of the file browser. Everything works fine, but the problem comes with displaying thumbnails of video/images. The loading of thumbnails  is too slow in the long grid view.  I'm just unable to come up with a better solution due to the lack of time. It would be great if your Module supports this feature. Thank you!

**Comment by spacecowboy** [comment]
Are you loading images with Glide as I do in the [sample app](https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/src/main/java/com/nononsenseapps/filepicker/sample/ImagePickerFragment.java)? 

Loading thumbnails in my camera directory is near-instant. What are you trying to display, and from where (internet or SD-card, images or huge video files)?

**Comment by LinkedHK** [comment]
Hey Thanks for your help. This library suits my needs :) I will give it a shot unless I get fired for the project overtime :)

**Comment by spacecowboy** [comment]
Haha, awesome. Just let me know if there's anything else.
