### ISSUE TITLE
Question here!

### ISSUE THREAD

**Issue by taimur97** [spacecowboy/NoNonsense-FilePicker#50]
It shows all hidden directories by default. In my app I don't want to show hidden directories what should I do to disable it from showing hidden folders?

**Comment by spacecowboy** [comment]
That depends on what you mean by "hidden". Do you mean files and directories which begin by a __.__ (dot)?

**Comment by taimur97** [comment]
Yes I mean the files and directories which begin with a dot(.)

**Comment by spacecowboy** [comment]
Have a look at this example in the Wiki:
https://github.com/spacecowboy/NoNonsense-FilePicker/wiki/Example:-Filter-on-file-extensions

But instead of filtering on the suffix (file-extension), you can filter on the prefix.

Basically, all you need to do in your fragment is override `isItemVisible` with the following:

```java
    @Override
    protected boolean isItemVisible(final File file) {
        return super.isItemVisible(file) && !getName(file).startsWith(".");
    }
```

And that will not include stuff that starts with a "." in the list.

**Comment by taimur97** [comment]
Hi 
Thanks for your fast support 
I also want to filter the files based on extensions and don't want to show files/dirs which start with a dot(.)
How can I get both of these functions to work?

I tried the following code 

  @Override
    protected boolean isItemVisible(final File file) {
        return super.isItemVisible(file) && !getName(file).startsWith(".") && EXTENSION.equalsIgnoreCase(getExtension(file));
    }
And also tried the following code but both don't work

 @Override
    protected boolean isItemVisible(final File file) {
        if (!isDir(file) && (mode == MODE_FILE || mode == MODE_FILE_AND_DIR) && !getName(file).startsWith(".")) {
            return EXTENSION.equalsIgnoreCase(getExtension(file));
        }
        return isDir(file);
    }

**Comment by spacecowboy** [comment]
Your two snippets both have different bugs. The first is easiest. You are hiding directories because they do not have file extensions. Here's what you actually want:

```java
public class FilterFragment extends FilePickerFragment {

    private static final List<String> EXTENSIONS = Arrays.asList(".jpg", ".os");

    /**
     *
     * @param file
     * @return The file extension. If file has no extension, it returns null.
     */
    private String getExtension(@NonNull File file) {
        String path = file.getPath();
        int i = path.lastIndexOf(".");
        if (i < 0) {
            return null;
        } else {
            return path.substring(i).toLowerCase();
        }
    }

    @Override
    protected boolean isItemVisible(final File file) {
        boolean sp = super.isItemVisible(file);
        if (isDir(file)) {
            // Directories do not have file extensions
            return sp && !getName(file).startsWith(".");
        } else {
            return sp && !getName(file).startsWith(".") && EXTENSIONS.contains(getExtension(file));
        }
    }
}
```

I have tested it and it works.

**Comment by taimur97** [comment]
Thanks so much it's working great :) :+1: 

Only one more think, I am using your library to pick videos is there anyway to show the thumbnails of videos in the filepicker fragment?

**Comment by spacecowboy** [comment]
Absolutely. Look at the code in the sample-app with image-previews. Use the exact same code. Glide is a fantastic library and also support video thumbnails. 

Here's what the fragment looks like with the code above combined with the image-sample:

```java
public class FilterFragment extends FilePickerFragment {

    private static final List<String> IMGEXTENSIONS = Arrays.asList(".jpg", ".png");
    private static final List<String> VIDEOEXTENSIONS = Arrays.asList(".mp4", ".avi");

    /**
     *
     * @param file
     * @return The file extension. If file has no extension, it returns null.
     */
    private String getExtension(@NonNull File file) {
        String path = file.getPath();
        int i = path.lastIndexOf(".");
        if (i < 0) {
            return null;
        } else {
            return path.substring(i).toLowerCase();
        }
    }

    /**
     * 
     * @param file to maybe add. Can be either a directory or file.
     * @return true for files which should be shown, false otherwise
     */
    @Override
    protected boolean isItemVisible(final File file) {
        boolean sp = super.isItemVisible(file);
        if (isDir(file)) {
            // Directories do not have file extensions
            return sp && !getName(file).startsWith(".");
        } else {
            final String ext = getExtension(file);
            return sp && !getName(file).startsWith(".") &&
                    (IMGEXTENSIONS.contains(ext) ||
                    VIDEOEXTENSIONS.contains(ext));
        }
    }

    /**
     * An extremely simple method for identifying images. This
     * could be improved, but it's good enough for this example.
     *
     * @param file which could be an image or a video
     * @return true if the file can be previewed, false otherwise
     */
    protected boolean isImageOrVideo(File file) {
        final String ext = getExtension(file);
        return !isDir(file) && (IMGEXTENSIONS.contains(ext) || VIDEOEXTENSIONS.contains(ext));

    }

    /**
     * Overriding this method allows us to inject a preview image
     * in the layout
     *
     * @param vh       to bind data from either a file or directory
     * @param position 0 - n, where the header has been subtracted
     * @param file     to show info about
     */
    @Override
    public void onBindViewHolder(DirViewHolder vh, int position, File file) {
        // Let the super method do its thing, we only care about the image
        // We could load a specific layout in oncreateviewholder, but
        // every item includes an image to hold the directory icon anyway
        super.onBindViewHolder(vh, position, file);

        // All we need to do is load the imageview with something useful, and make it visible
        if (isImageOrVideo(file)) {
            vh.icon.setVisibility(View.VISIBLE);
            Glide.with(this).load(file).centerCrop().into((ImageView) vh.icon);
        }
    }
}
```

Loading thumbnails for images is super fast, but videos require a little bit of processing (no way around this fact). But, once it's done it, it caches the images, so scrolling is still super smooth.

**Comment by spacecowboy** [comment]
Remember to include Glide as a dependency in your build.gradle:

```
compile 'com.github.bumptech.glide:glide:3.5.2'
```

as seen here: [Sample build.gradle](https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/build.gradle)

**Comment by taimur97** [comment]
Yeah I already had glide in my project :)
I tested the code and it works but the thumbnails were not displaying in Samsung nexus with android 4.3 and 4.2 
I also tested it on LG g2, nexus 5, nexus 7 and nvidia shield all with android version => 5 and all the video thumbnails were being displayed.
I don't know if it was the problem with the Samsung Nexus or it doesn't work correctly on devices with android version below 5 and I don't have any other phone with android version below 5 

This is how it looks on Samsung nexus 
![samsung galaxy nexus 1](https://cloud.githubusercontent.com/assets/2510169/9644634/ab0eaef6-51e0-11e5-867c-cf2eefd2c889.png)

**Comment by spacecowboy** [comment]
Might be a Glide issue. You could of course load thumbnails yourself using [ThumbnailUtils](http://developer.android.com/reference/android/media/ThumbnailUtils.html#createVideoThumbnail%28java.lang.String,%20int%29) but you'll to handle threading so you don't do image transformations on the UI-thread (which Glide does for you).

Another option of course is simply not to show thumbnails on Android <= 21

**Comment by spacecowboy** [comment]
I get the same issue when running an emulator on 4.0.3 (with images) so it's probably not a Samsung thing.

**Comment by spacecowboy** [comment]
I think they might have fixed it but not released it yet:
https://github.com/bumptech/glide/commit/f97dc0d713ec45fff6ad857e909bf659740aaf7d

Try building the jar-file yourself from latest master and see if that fixes it.

**Comment by taimur97** [comment]
Hi 
The problem is not with glide. It does show thumbnails on android with version below 5 because in my app I am using glide to show the thumbnails of videos and it works fine on all android versions. The issue is with your lib please try to investigate it.
BTW sorry for my late reply was busy with my app

**Comment by spacecowboy** [comment]
Found the issue. Problem was that older android versions don't handle the "tint" functionality in the support library correctly.

See the updated sample code in aa54b90 an example fix. Essentially, provide your own layouts for image files which do not contain `android:tint` on the imageviews.

**Comment by Scrounger** [comment]
@spacecowboy 
Great library, thanks a lot!

How can i change the dialog tittle and the hint of new folder dialog?

**Comment by spacecowboy** [comment]
Thanks :)

That dialog is defined here:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/res/layout/nnf_dialog_folder_name.xml

So override `nnf_name`, or set it to your own string resource.

The title is set here:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/java/com/nononsenseapps/filepicker/NewItemFragment.java#L45

So override `nnf_new_folder` for that.

Please create new issues for questions in the future. There's a risk that I miss them otherwise.
