### ISSUE TITLE
Spacing of filename items

### ISSUE THREAD

**Issue by Mathbl** [spacecowboy/NoNonsense-FilePicker#52]
I feel like the spacing/padding of the items should be 16dp instead of 8dp.

It should align with the folder icons.

Thanks!

**Comment by spacecowboy** [comment]
Thanks for the opinion. I might change it. 

Just in case you didn't know, you can load custom layouts with the padding adjusted, if you want.

**Comment by Mathbl** [comment]
Yes, sorry for not reporting back, but I finally dug through the repo and found the post about overriding. I did just that and customized it. 

Good job, it seems to work very well. Thank you.
