### ISSUE TITLE
lower minSdk

### ISSUE THREAD

**Issue by marbat87** [spacecowboy/NoNonsense-FilePicker#54]
Hi,

Is there any chance to lower the minSdk to 9?
I imported the project locally and with just a couple of fixes it works great on this API level, without adding any import or anything similar.

I can make a pull request in case.
Let me know.

Thanks & regards,
Marcello

**Comment by spacecowboy** [comment]
I'd be happy to review the changes and make a decision based on that. But I'm quite surprised anyone is still developing for Gingerbread anymore.

**Comment by marbat87** [comment]
@spacecowboy  Done :) #55 

Regards,
Marcello

**Comment by spacecowboy** [comment]
Fixed in #55
