### ISSUE TITLE
Never gettings result ok in onActivityResult

### ISSUE THREAD

**Issue by lfdversluis** [spacecowboy/NoNonsense-FilePicker#57]
Whenever I run the directory selector, I never get RESULT_OK. I only get ``3561 -1 Intent { dat=file:///storage/emulated/0/Download }`` for ``protected void onActivityResult(int requestCode, int resultCode, Intent data) { Log.e("Directory", String.format("%s %s %s", requestCode, resultCode, data)); ... }``

This is my code I use to open the screen:

```
 // This always works
        Intent i = new Intent(this, FilePickerActivity.class);

        // Set these depending on your use case. These are the defaults.
        i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
        i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
        i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_DIR);

        // Configure initial directory by specifying a String.
        // You could specify a String like "/storage/emulated/0/", but that can
        // dangerous. Always use Android's API calls to get paths to the SD-card or
        // internal memory.
        i.putExtra(FilePickerActivity.EXTRA_START_PATH, Environment.getExternalStorageDirectory().getPath());

        startActivityForResult(i, DIR_CODE);
```

**Comment by spacecowboy** [comment]
This seems odd. Does it also happen when you set `EXTRA_ALLOW_MULTIPLE = true` ?

And what version of Android are you doing this on?

**Comment by lfdversluis** [comment]
I am using Android 5.0.1, I will try settings that settings.

**Comment by lfdversluis** [comment]
This time I get
```
3561 -1 Intent { (has clip) (has extras) }
E/URI1: /storage/extSdCard/DCIM/Camera
```

So settings that boolean flag does trigger something that works.

**Comment by spacecowboy** [comment]
Actually, I looked in the source and you **are** getting `RESULT_OK`.

Go to the source of `Activity.java` in Android and you'll see:

```
    /** Standard activity result: operation canceled. */
    public static final int RESULT_CANCELED    = 0;
    /** Standard activity result: operation succeeded. */
    public static final int RESULT_OK           = -1;
    /** Start of user-defined activity results. */
    public static final int RESULT_FIRST_USER   = 1;
```

And `-1` is exactly what the app is returning.

**Comment by lfdversluis** [comment]
Oh my, you are absolutely correct. I was expecting the "URI2" to trigger, which it shouldn't. The last else case should've triggered indeed and after testing this, it does. Sorry for the confusion! :+1: 

Perhaps you could add it in the sample so people like me are not getting the wrong idea?
```
else {
    Uri uri = data.getData();
    // Do something with the URI
    Log.e("URI3", uri.getPath());
}
```

Thanks for the nice library btw!

**Comment by spacecowboy** [comment]
Oh I see. You thought the `else` was connected with the outer `if` where `RESULT_OK` is specified.

Whereas the logic can be summarized as:

```
if (ok) {
    if (multiple) {
        if (jellybean) {
             // Do stuff with multiple
        } else { // kitkat
            // Do stuff with multiple
        }
    } else { // single
        // Do stuff with single
    }
}
```

I'm all for making the samples clearer. But I'm not sure your Log to error makes sense? (Why are you logging a non-error to error? Why not use debug (Log.d) instead?)

**Comment by lfdversluis** [comment]
I was debugging and since I had quite some background noise from a library, so I filtered on error and used ``Log.e``. By all means, use ``Log.d`` or even ``Log.v``

**Comment by spacecowboy** [comment]
Ah ok. But still, would the Log statement really make the example clearer?

**Comment by lfdversluis** [comment]
Only to show what has triggered, but maybe that's not necessary. If you think it doesn't add too much, you may want to leave it out.

**Comment by spacecowboy** [comment]
I'll give it some thought. Thanks for the feedback
