### ISSUE TITLE
probebly underscore missing

### ISSUE THREAD

**Issue by kuldeepdhaka** [spacecowboy/NoNonsense-FilePicker#63]
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/java/com/nononsenseapps/filepicker/AbstractFilePickerFragment.java#L73

`protected static final String KEY_CURRENT_PATH = "KEY_CURRENT PATH";`
shouldn't it be `"KEY_CURRENT_PATH"`

**Comment by spacecowboy** [comment]
Haha, yes it should indeed. I don't think it impacts anyone though. But it should be changed for consistency.
