### ISSUE TITLE
Picker crashes in versions > 2.4.2 if theme is not set

### ISSUE THREAD

**Issue by psyren89** [spacecowboy/NoNonsense-FilePicker#64]
As the title implies, the picker will crash if the theme/colour values are not set in a similar fashion to what's outlined in the readme. The logcat states that an XML inflation exception is the cause.

**Comment by psyren89** [comment]
The solution is to (properly?) set the themes.

**Comment by spacecowboy** [comment]
Yes, the theme is required and it will crash if you don't set the theme.
