### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by sagits** [spacecowboy/NoNonsense-FilePicker#67]
Hi, how can i change the file picker background color? Thanks in advance.

**Comment by spacecowboy** [comment]
Go into settings and select your theme. There is light, dark, and black.

**Comment by spacecowboy** [comment]
Sorry about my earlier reply, thought the question was on another one of my projects.

Change the theme to have the background you want. For example, to do it in the sample, you could set the background as:

`<item name="android:windowBackground">@color/some_bg_color</item>`

You'd do that in your app's themes, see
 https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/src/main/res/values/styles.xml

**Comment by sagits** [comment]
Thank you, but now i need to change the text color, how can i do that?

2016-01-25 6:42 GMT-02:00 Space Cowboy <notifications@github.com>:

> Sorry about my earlier reply, thought the question was on another one of
> my projects.
>
> Change the theme to have the background you want. For example, to do it in
> the sample, you could set the background as:
>
> <item name="android:windowBackground">@color/some_bg_color</item>
>
> You'd do that in your app's themes, see
>
> https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/src/main/res/values/styles.xml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spacecowboy/NoNonsense-FilePicker/issues/67#issuecomment-174438139>
> .
>



-- 

Renato Probst
Desenvolvedor Android e Web
41 9197-4873

**Comment by spacecowboy** [comment]
By setting `textColorPrimary` in the theme.

Here are some links to information about Android themes:
https://gist.github.com/boxme/1fec2a44cc46fad221ee
http://treyrobinson.net/blog/android-l-tutorials-part-2-material-theme-colors/
http://developer.android.com/guide/topics/ui/themes.html
http://developer.android.com/training/material/theme.html#Inheritance
