### ISSUE TITLE
Custom view

### ISSUE THREAD

**Issue by fmeneuhe** [spacecowboy/NoNonsense-FilePicker#70]
Hi,
Is possible to use a custom view? I want to do a custom view to add favs icons such as an external SD icon to quickly go the external SD card, so the user has not to browse directories. 
Thanks

**Comment by spacecowboy** [comment]
Everything is technically possible. Just create a child-class and override the layout it uses. The wiki has an example of how to use custom list item layouts here: https://github.com/spacecowboy/NoNonsense-FilePicker/wiki/Example:-Custom-listitem-layouts-to-display-long-filenames

It's basically the same approach you'd take. But the method you're interested in overriding is this one:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/java/com/nononsenseapps/filepicker/AbstractFilePickerFragment.java#L127

Override that method and load whatever custom view you want. Just remember to NOT call `super.onCreateView`.  If you find something to be particularly difficult (which could be easier), tell me and I'll see if something can be done to make it easier :)
