### ISSUE TITLE
going back in path

### ISSUE THREAD

**Issue by ahmet12** [spacecowboy/NoNonsense-FilePicker#72]
FilteredFilePickerFragment.java
app crashes when you go back with (..). You may add this line;  if (getExtension(file)!=null) 

protected boolean isItemVisible(final File file) {
        boolean ret = super.isItemVisible(file);
        if (ret && !isDir(file) && (mode == MODE_FILE || mode == MODE_FILE_AND_DIR)) {
            // ret = EXTENSION.equalsIgnoreCase(getExtension(file));
            if (getExtension(file)!=null)
            ret = EXTENSION.contains(getExtension(file));
        }
        return ret;
    }

**Comment by spacecowboy** [comment]
Thanks for highlighting this. I've updated the wiki to handle nulls better here.

(marked question so this does not end up in the changelog)
