### ISSUE TITLE
Dropbox sample crash if multiple press on folder

### ISSUE THREAD

**Issue by Shashank066** [spacecowboy/NoNonsense-FilePicker#73]
I tried to use it as a Dropbox folder picker. I am able to browse and select folders using the DropboxFilePickerActivity from your sample. The only issue is if you press on a folder it waits for the subfolders to loads and then changes the UI list. If the user presses the folder name multiple times a crash occurs. The folder loading may take a long time for some users due to unstable nature of mobile networks. Ideal behaviour would be to show a Indeterminate progress bar in place of list when user chooses a folder. When the sub folder list is loaded the progress bar should be hidden and sub list shown. Kind of like the progress bar as an empty view for the list and an empty list while subfolders are loading.
Other than that it's a nice library. It's the most suitable folder picker when compared to any other library.

**Comment by spacecowboy** [comment]
Thanks, will get this sorted.

**Comment by spacecowboy** [comment]
Added the suggestion to its own issue (for changelog reasons): https://github.com/spacecowboy/NoNonsense-FilePicker/issues/74

**Comment by Shashank066** [comment]
Thanks a lot. Looks nice now with progress bar.
