### ISSUE TITLE
Crash while creating folder in dropbox sample

### ISSUE THREAD

**Issue by Shashank066** [spacecowboy/NoNonsense-FilePicker#76]
In the dropbox sample there is a crash while creating a new folder. Moving the refresh from doInBackground to onPostExecute fixes it.

` private class FolderCreator extends AsyncTask<String, Void, Void> {

        @Override
        protected Void doInBackground(final String... paths) {
            for (String path : paths) {
                try {
                    dbApi.createFolder(path);
                    mCurrentPath = dbApi.metadata(path, 1, null, false, null);
                } catch (DropboxException e) {
                    Toast.makeText(getActivity(), R.string.nnf_create_folder_error,
                            Toast.LENGTH_SHORT).show();
                }
            }
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            refresh();
        }
    }`

**Comment by spacecowboy** [comment]
Awesome. Thanks for the report. I updated the sample app accordingly: https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/2.5.2

(No new version since the library itself did not get any changes)
