### ISSUE TITLE
Canceled result

### ISSUE THREAD

**Issue by WeaponMan** [spacecowboy/NoNonsense-FilePicker#77]
Hi,
I am running this library on API 16 device.

When I start FilePickerActivity then I almost instantly get RESULT_CANCELED.

` 
        Intent i = new Intent(getActivity(), FilePickerActivity.class);
        i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
        i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
        i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);
        i.putExtra(FilePickerActivity.EXTRA_START_PATH,
                Environment.getExternalStorageDirectory().getPath());
        getActivity().startActivityForResult(i, MainActivity.DOCUMENT_ADD_FILE_CODE);
`

**Comment by spacecowboy** [comment]
Did find a fix for your issue?

**Comment by WeaponMan** [comment]
Yes, I have removed singleInstance from Activity in AndroidManifest.
On API 21> this works without issue with singleInstance Activity.
