### ISSUE TITLE
Filter for file picker

### ISSUE THREAD

**Issue by usman-ghauri** [spacecowboy/NoNonsense-FilePicker#79]
Is there any way i can filter the filer picker to only show and pick certain type of files? is so there is no sample about it. please let me know how i can achieve. i only want user to pick txt's, pdf's, doc and other document files.

**Comment by spacecowboy** [comment]
Yes there is! The [Wiki](https://github.com/spacecowboy/NoNonsense-FilePicker/wiki) has an example for just this use-case:

https://github.com/spacecowboy/NoNonsense-FilePicker/wiki/Example:-Filter-on-file-extensions

Just change the ".txt" constant to be a list basically

**Comment by AanalShah** [comment]
i m trying to set multiple extenstion but its don't work please anyone help me
 i m declar array ;
` private static final String[] EXTENSION = {".docx",".pdf",".doc"};`

`for(int i=0;i<=2;i++) {
            if (!isDir(file) && (mode == MODE_FILE || mode == MODE_FILE_AND_DIR)) {
              String ext = getExtension(file);
              return ext != null && EXTENSION[i].equalsIgnoreCase(ext);
            }

        }`

**Comment by spacecowboy** [comment]
@AanalShah as i mentioned in https://github.com/spacecowboy/NoNonsense-FilePicker/issues/37, if you want to filter on multiple extensions, you can for example do this


```java
List<String> places = Arrays.asList("mp3", "wav", "ogg");
```

You could for example do:

```java
return ExtensionsList.contains(getExtension(file).toLowerCase());
```

Instead of the example's
```java
return EXTENSION.equalsIgnoreCase(getExtension(file));
```

**Comment by AanalShah** [comment]
hey thank a lot
perfect

**Comment by usman-ghauri** [comment]
you're suggesting i change your source code. but i've imported your project as a dependendy and android studio wont allow me to change any LOC in your file. i suggest you generalize this approach. for example, let us decide to apply filter at this level

`        Intent i = new Intent(getActivity(), FilePickerActivity.class);

// here we apply a filter list on that activity going to launch
///

        i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
        i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
        i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);
        // Configure initial directory by specifying a String.
        // You could specify a String like "/storage/emulated/0/", but that can
        // dangerous. Always use Android's API calls to get paths to the SD-card or
        // internal memory.
        i.putExtra(FilePickerActivity.EXTRA_START_PATH, Environment.getExternalStorageDirectory().getPath());
        startActivityForResult(i, 0);`

just a suggestion to genralize more. i saw another file picker library that applies filter on intent level. your library pro is that it works fine on kindle fire and works according to lower api devices as well. looking forward to new updates

**Comment by spacecowboy** [comment]
@usman-ghauri No I am not. You are supposed to create your own fragment and activity and inherit from the library's fragment. The example's That way you can override any logic without asking me to implement it for you. It doesn't get any more general than that.

This is clearly explained in the wiki: https://github.com/spacecowboy/NoNonsense-FilePicker/wiki
