### ISSUE TITLE
gradle 

### ISSUE THREAD

**Issue by yeganehaym** [spacecowboy/NoNonsense-FilePicker#86]
hello sir
i entered this address
  compile 'com.nononsenseapps:filepicker:2.5.2'
but it doesn't work

**Comment by spacecowboy** [comment]
Could you be more specific? If you post the gradle log I might be able to help you.

**Comment by yeganehaym** [comment]
failed to resolve <package name>

**Comment by spacecowboy** [comment]
that's not a log
