### ISSUE TITLE
Fast Scroll

### ISSUE THREAD

**Issue by ninjagoat** [spacecowboy/NoNonsense-FilePicker#87]
Please add fast scroll to the RecyclerView.
I use [this library](https://github.com/timusus/RecyclerView-FastScroll) for my projects which works pretty well.

**Comment by spacecowboy** [comment]
Good suggestion, but I don't think I will. I prefer to keep the library as minimal as possible.

However, it is entirely possible to do this in your own app by overriding the layout which is loaded (and some other things).

I'll add an example to the Wiki.

**Comment by ninjagoat** [comment]
Well the library is only around ~40 kB. So, I don't really think it adds too much, while providing useful functionality which very few would probably dislike. But anyway, thanks for your reply.

**Comment by spacecowboy** [comment]
It has nothing to do with physical size, but with code bloat. It is a goal to make the library have as little code and dependencies as possible.

Another side-effect of FastScroller is also raising the minSDK number from 9 to 11. A minor issue to be sure, but still unwanted.

I added an example implementation to the sample app now. It revealed a couple of private fields that should have been protected, so motivated a new patch release which is good.
