### ISSUE TITLE
Error implementing!

### ISSUE THREAD

**Issue by XxGoliathusxX** [spacecowboy/NoNonsense-FilePicker#90]
Failed to resolve: com.android:support:recyclerview-v7:23.4.0

**Comment by spacecowboy** [comment]
you need to update the Android support repository in your Android SDK. See
this link for instructions
https://developer.android.com/studio/intro/update.html#sdk-manager

**Comment by XxGoliathusxX** [comment]
I will try this. Thank you a lot!
