### ISSUE TITLE
integration with preferences

### ISSUE THREAD

**Issue by shankar667** [spacecowboy/NoNonsense-FilePicker#93]
Hi,

Can you give me a sample code to integrate with preferences?

**Comment by spacecowboy** [comment]
I'd be happy to, if you can be more specific. What do you mean when you say 
> integrate with preferences?

**Comment by shankar667** [comment]
I mean, how can i add in preferences settings?

**Comment by spacecowboy** [comment]
You can see an example of that in NoNonsense Notes.

This is the relevant lines in the preference xml: https://github.com/spacecowboy/NotePad/blob/master/app/src/main/res/xml/app_pref_sync.xml#L72

And these are the relevant lines in the `PreferenceFragment` which handles when the user presses that preference:

https://github.com/spacecowboy/NotePad/blob/master/app/src/main/java/com/nononsenseapps/notepad/prefs/SyncPrefs.java#L195

https://github.com/spacecowboy/NotePad/blob/master/app/src/main/java/com/nononsenseapps/notepad/prefs/SyncPrefs.java#L271

https://github.com/spacecowboy/NotePad/blob/master/app/src/main/java/com/nononsenseapps/notepad/prefs/SyncPrefs.java#L329

**Comment by shankar667** [comment]
Thank you!
