### ISSUE TITLE
FILE_CODE

### ISSUE THREAD

**Issue by paragverma** [spacecowboy/NoNonsense-FilePicker#94]
I'm following all steps from readme,

I'm getiing "Cannot resolve FILE_CODE"

    if(view.getId() == R.id.add_timetable){
            // This always works
            Intent i = new Intent(Admin_Dashboard.this, FilePickerActivity.class);
            // This works if you defined the intent filter
            // Intent i = new Intent(Intent.ACTION_GET_CONTENT);

            // Set these depending on your use case. These are the defaults.
            i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
            i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
            i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);

            // Configure initial directory by specifying a String.
            // You could specify a String like "/storage/emulated/0/", but that can
            // dangerous. Always use Android's API calls to get paths to the SD-card or
            // internal memory.
            i.putExtra(FilePickerActivity.EXTRA_START_PATH, Environment.getExternalStorageDirectory().getPath());

            startActivityForResult(i, FILE_CODE);
        }

**Comment by shankar667** [comment]
define FILE_CODE in your activity.

int FILE_CODE = 1 ; //any number you want

**Comment by spacecowboy** [comment]
Yes @paragverma , just define a constant in your class (any number works, it just has to be unique if you use any other `activityForResult()`:

```java
private static final int FILE_CODE = 1;
```
