### ISSUE TITLE
Image preview in Folder

### ISSUE THREAD

**Issue by Scrounger** [spacecowboy/NoNonsense-FilePicker#95]
@spacecowboy 

Is it possible to show a preview image if the file is an image?

**Comment by spacecowboy** [comment]
@Scrounger Yes! This is included in the sample-app. You can view the code here: https://github.com/spacecowboy/NoNonsense-FilePicker/tree/master/sample/src/main/java/com/nononsenseapps/filepicker/sample/multimedia
