### ISSUE TITLE
Feature: RecyclerView.ItemDecoration 

### ISSUE THREAD

**Issue by Scrounger** [spacecowboy/NoNonsense-FilePicker#97]
@spacecowboy:

Could you please implement using custom RecyclerViewItemDecoration, e.g. using a divider.

`public class RecyclerDividerItemDecoration extends RecyclerView.ItemDecoration {

    private Drawable mDivider;

    public RecyclerDividerItemDecoration(Drawable divider) {
        mDivider = divider;
    }

    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        super.getItemOffsets(outRect, view, parent, state);

        if (parent.getChildAdapterPosition(view) == 0) {
            return;
        }

        outRect.top = mDivider.getIntrinsicHeight();
    }

    @Override
    public void onDraw(Canvas canvas, RecyclerView parent, RecyclerView.State state) {
        int dividerLeft = parent.getPaddingLeft();
        int dividerRight = parent.getWidth() - parent.getPaddingRight();

        int childCount = parent.getChildCount();
        for (int i = 0; i < childCount - 1; i++) {
            View child = parent.getChildAt(i);

            RecyclerView.LayoutParams params = (RecyclerView.LayoutParams) child.getLayoutParams();

            int dividerTop = child.getBottom() + params.bottomMargin;
            int dividerBottom = dividerTop + mDivider.getIntrinsicHeight();

            mDivider.setBounds(dividerLeft, dividerTop, dividerRight, dividerBottom);
            mDivider.draw(canvas);
        }
    }
}`

called by:
`mRecyclerView.addItemDecoration(new RecyclerDividerItemDecoration(dividerDrawable));`

my Idea is to have an intent.putExtra using the drawable int?

**Comment by spacecowboy** [comment]
Hmm, not everyone will want a divider. Since this can't be defined in a theme, I'll make some changes so that it can be overridden easily.

**Comment by spacecowboy** [comment]
Adding divider support in themes turned out to be easy. Fixed this in #99

**Comment by Scrounger** [comment]
@spacecowboy 
Perfect, thanks for the implementation!
